### ISSUE TITLE
Modify the content from lorem ipsum to valid data

### ISSUE THREAD

**Issue by Sushant2** [Sushant2/Jungle-Tour#1]
In the website, u'll encounter lorem ipsum, change it to valid & correct data!

**Comment by Teleri** [comment]
Hello - do you have actual data you wish to be used? As I'll be happy to do this

**Comment by badal-cloud** [comment]
Please assign to me this issue!!

**Comment by mishrashree18** [comment]
I want to work on it, can you please assign me this issue?
