### ISSUE TITLE
Update the README.md file!

### ISSUE THREAD

**Issue by Sushant2** [Sushant2/Jungle-Tour#4]
As our site content is changed recently!
So,, create an awesome readme about descripting the Jungle-Tour!!!

**Comment by bineetNaidu** [comment]
I would like to contribute on this issue, feel free to assign me this task to complete. :smile:

**Comment by Sushant2** [comment]
> I would like to contribute on this issue, feel free to assign me this task to complete. 😄

Okay!
Go ahead & create one!
But the readme should be impressive!!!
